---
- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jre-headless
    state: present

- name: Add Jenkins GPG Key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins Repo
  shell: |
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start Jenkins Service
  service:
    name: jenkins
    state: started
    enabled: yes